---
title: "Beat Salad - EDA"
author: "Michael Ellsworth"
date: '2020-02-08'
output: html_document
---

```{r}
library(tidyverse)
library(stringr)
```

```{r Read CSVs and combine, message=FALSE, warning=FALSE}
BS <- read_csv('BeatSalad.csv')
BSTD <- read_csv('BeatSaladToDate.csv')
disco <- read_csv('Disco.csv')
pop <- read_csv('Pop.csv')
combined_playlists <- rbind(BS, disco, pop)
```

```{r}
spotify_hist <- function(df, feature, html_col_code)
{
  df %>%
    ggplot(aes(x = !!enquo(feature))) +
    geom_histogram(fill = html_col_code, aes(y=..count../sum(..count..))) +
    ylab("Frequency - Normalized") +
    xlab("Value") +
    scale_y_continuous(expand = c(0,0)) +
    scale_x_continuous(expand = c(0,0),
                       breaks = c(0.0, 0.2, 0.4, 0.6, 0.8, 1.0),
                       limits = c(-0.1, 1.1)) +
    theme(
  panel.background = element_rect(fill = "white",
                                colour = "white",
                                size = 0.5, linetype = "solid"),
  panel.grid.major = element_line(size = 0.5, linetype = 'solid',
                                colour = "white"), 
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid',
                                colour = "white"),
  panel.border = element_rect(colour = "black", fill=NA, size=0.8),
  plot.title = element_text(hjust = 0.5)
  )
}
```

```{r Create Boxplots for Disco}
disco %>%
  select(valence, danceability, energy) %>%
  mutate(Danceability = danceability, Energy = energy, Positivity = valence) %>%
  gather(key = feature, value = value, Positivity, Danceability, Energy) %>%
  ggplot(aes(x = feature, y = value)) +
  geom_boxplot(alpha = 0.5, fill = "#00BFC4") +
  scale_y_continuous(limits = c(0,1)) +
  theme(legend.position = "none") +
  xlab("Track Features") +
  ylab("Value of Feature") +
  ggtitle("Disco is generally danceable, energetic and positive!")
```

```{r Create Histograms for Disco}
spotify_hist(disco, energy, "#C0C0C0") + ggtitle("Energy - Beat Salad")
spotify_hist(disco, danceability, "#C0C0C0") + ggtitle("Danceability - Beat Salad")
```

```{r Create Histograms for Beat Salad}
spotify_hist(BS, energy, "#8B008B") + ggtitle("Energy - Beat Salad")
spotify_hist(BS, danceability, "#8B008B") + ggtitle("Danceability - Beat Salad")
spotify_hist(BS, valence, "#8B008B") + ggtitle("Valence - Beat Salad")
spotify_hist(BS, instrumentalness, "#F8766D") + ggtitle("Instrumentalness - Beat Salad") +
  theme(text = element_text(size=13))
```

```{r}
plot_multi_histogram <- function(df, feature, label_column) {
    plt <- ggplot(df, aes(x=eval(parse(text=feature)), fill=eval(parse(text=label_column)))) +
    geom_histogram(alpha=0.5, position="identity", aes(y = ..density..), color="black") +
    labs(x=feature, y = "Density")
    plt + guides(fill=guide_legend(title="Playlist"))
}
combined_playlists %>%
  filter(playlist_name == "Disco" | playlist_name == "Beat Salad") %>%
  plot_multi_histogram('energy', 'playlist_name') +
  xlab("Energy of Tracks") +
  ylab("Density of Feature") +
  theme(text = element_text(size=13)) +
  ggtitle("Energy: Beat Salad versus disco")

combined_playlists %>%
  filter(playlist_name == "Disco" | playlist_name == "Beat Salad") %>%
  plot_multi_histogram('danceability', 'playlist_name') +
  xlab("Danceability of Tracks") +
  ylab("Density of Feature") +
  theme(text = element_text(size=13)) +
  ggtitle("Danceability: Beat Salad versus disco")

combined_playlists %>%
  filter(playlist_name == "Disco" | playlist_name == "Beat Salad") %>%
  plot_multi_histogram('valence', 'playlist_name') +
  xlab("Positivity of Tracks") +
  ylab("Density of Feature") +
  theme(text = element_text(size=13)) +
  ggtitle("Positivity: Beat Salad versus disco")
```

```{r}
combined_playlists %>%
  filter(playlist_name == "Pop" | playlist_name == "Beat Salad") %>%
  plot_multi_histogram('track.popularity', 'playlist_name') +
  xlab("Popularity of Tracks") +
  ylab("Density of Feature") +
  scale_fill_manual(values=c("#F8766D", "#00BA38")) +
  theme(text = element_text(size=13)) +
  ggtitle("Popularity: Beat Salad versus pop music")
```


```{r Create new column Track Numbers for Beat Salad to Date}
BSTD$track_number <- c(seq(1, 21, 1), seq(1, 16, 1), seq(1, 21, 1), seq(1, 20, 1))
BSTD$episode_number <- c(rep("1", 21),
                      rep("2", 16),
                      rep("3", 21),
                      rep("4", 20))
```

```{r Energy Versus Track Number Beat Salad To Date}
BSTD_means <- BSTD %>%
  group_by(track_number) %>%
  mutate(energy_mean = mean(energy)) %>%
  mutate(energy = energy_mean) %>%
  ungroup() %>%
  mutate(episode_number = "mean")
BSTD_means <- BSTD_means[1:21, ]

BSTD %>%
  group_by(track_number) %>%
  mutate(energy_mean = mean(energy)) %>%
  ungroup() %>%
  rbind(BSTD_means) %>%
  ggplot(aes(x = track_number, y = energy, col = episode_number)) +
  geom_point() +
  geom_line(aes(x = track_number, y = energy_mean), col = "black", size = 3) +
  geom_line() +
  ylab("Track Energy") +
  xlab("Track Number") +
  scale_y_continuous(limits = c(0, 1), expand = c(0,0)) +
  scale_color_manual(name = "Episode Number", values=c("#F8766D", "#00BA38", "#00BFC4", "#C77CFF", "black")) +
  theme(legend.position = "bottom", text = element_text(size=15)) +
  annotate("text", x = 18, y = 0.85, label = "Mean of the episodes") +
  annotate("segment", x = 17.5, y = 0.82, xend = 15.5, yend = 0.48, arrow = arrow(), size = 1) +
  ggtitle("Each episode's energy has a natural flow to it from start to finish!")
```
